name: Tests

on:
  pull_request:
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: bahmutov/npm-install@v1
      - run: yarn test
