name: typescript

on:
  pull_request:

jobs:
  typescript:
    name: typescript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: cd gcloud-functions/functions/ && yarn install && cd ../../
      - run: yarn tsc
